#!/bin/bash

# Demo script - Shows sample interaction

echo "╔════════════════════════════════════════╗"
echo "║  CP PROGRESS TRACKER - DEMO            ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "This application provides:"
echo ""
echo "✓ Menu-driven interface"
echo "✓ Add/View/Update/Delete problems"
echo "✓ Track progress statistics"
echo "✓ Filter by difficulty and status"
echo "✓ Auto-calculate accuracy"
echo ""
echo "========================================="
echo "Sample Menu:"
echo "========================================="
echo "1. Add Problem"
echo "2. View All Problems"
echo "3. Mark Problem as Solved"
echo "4. Delete Problem"
echo "5. View Progress"
echo "6. Exit"
echo "========================================="
echo ""
echo "To run the application:"
echo "  ./run.sh"
echo ""
echo "Or:"
echo "  java -cp \"lib/*:bin\" com.cptracker.ui.ConsoleUI"
echo ""
